[theme]
primaryColor = "#E24A33"  # Rouge ESCP
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F9"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true 